// Generated by gencpp from file aviot_srvs/DeleteFenceRequest.msg
// DO NOT EDIT!


#ifndef AVIOT_SRVS_MESSAGE_DELETEFENCEREQUEST_H
#define AVIOT_SRVS_MESSAGE_DELETEFENCEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aviot_srvs
{
template <class ContainerAllocator>
struct DeleteFenceRequest_
{
  typedef DeleteFenceRequest_<ContainerAllocator> Type;

  DeleteFenceRequest_()
    : polygon_id(0)  {
    }
  DeleteFenceRequest_(const ContainerAllocator& _alloc)
    : polygon_id(0)  {
  (void)_alloc;
    }



   typedef int32_t _polygon_id_type;
  _polygon_id_type polygon_id;





  typedef boost::shared_ptr< ::aviot_srvs::DeleteFenceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aviot_srvs::DeleteFenceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DeleteFenceRequest_

typedef ::aviot_srvs::DeleteFenceRequest_<std::allocator<void> > DeleteFenceRequest;

typedef boost::shared_ptr< ::aviot_srvs::DeleteFenceRequest > DeleteFenceRequestPtr;
typedef boost::shared_ptr< ::aviot_srvs::DeleteFenceRequest const> DeleteFenceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aviot_srvs::DeleteFenceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aviot_srvs::DeleteFenceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aviot_srvs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'HasHeader': False, 'IsFixedSize': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::aviot_srvs::DeleteFenceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aviot_srvs::DeleteFenceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aviot_srvs::DeleteFenceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aviot_srvs::DeleteFenceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aviot_srvs::DeleteFenceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aviot_srvs::DeleteFenceRequest_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aviot_srvs::DeleteFenceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "97f1028fa479966162ae92d2c0f9e429";
  }

  static const char* value(const ::aviot_srvs::DeleteFenceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x97f1028fa4799661ULL;
  static const uint64_t static_value2 = 0x62ae92d2c0f9e429ULL;
};

template<class ContainerAllocator>
struct DataType< ::aviot_srvs::DeleteFenceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aviot_srvs/DeleteFenceRequest";
  }

  static const char* value(const ::aviot_srvs::DeleteFenceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aviot_srvs::DeleteFenceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 polygon_id\n\
";
  }

  static const char* value(const ::aviot_srvs::DeleteFenceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aviot_srvs::DeleteFenceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.polygon_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DeleteFenceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aviot_srvs::DeleteFenceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aviot_srvs::DeleteFenceRequest_<ContainerAllocator>& v)
  {
    s << indent << "polygon_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.polygon_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AVIOT_SRVS_MESSAGE_DELETEFENCEREQUEST_H
