// Generated by gencpp from file aviot_srvs/ResetFence.msg
// DO NOT EDIT!


#ifndef AVIOT_SRVS_MESSAGE_RESETFENCE_H
#define AVIOT_SRVS_MESSAGE_RESETFENCE_H

#include <ros/service_traits.h>


#include <aviot_srvs/ResetFenceRequest.h>
#include <aviot_srvs/ResetFenceResponse.h>


namespace aviot_srvs
{

struct ResetFence
{

typedef ResetFenceRequest Request;
typedef ResetFenceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetFence
} // namespace aviot_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aviot_srvs::ResetFence > {
  static const char* value()
  {
    return "f0fad9ccd7b64cd66ec986070ce0fd3f";
  }

  static const char* value(const ::aviot_srvs::ResetFence&) { return value(); }
};

template<>
struct DataType< ::aviot_srvs::ResetFence > {
  static const char* value()
  {
    return "aviot_srvs/ResetFence";
  }

  static const char* value(const ::aviot_srvs::ResetFence&) { return value(); }
};


// service_traits::MD5Sum< ::aviot_srvs::ResetFenceRequest> should match 
// service_traits::MD5Sum< ::aviot_srvs::ResetFence > 
template<>
struct MD5Sum< ::aviot_srvs::ResetFenceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aviot_srvs::ResetFence >::value();
  }
  static const char* value(const ::aviot_srvs::ResetFenceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aviot_srvs::ResetFenceRequest> should match 
// service_traits::DataType< ::aviot_srvs::ResetFence > 
template<>
struct DataType< ::aviot_srvs::ResetFenceRequest>
{
  static const char* value()
  {
    return DataType< ::aviot_srvs::ResetFence >::value();
  }
  static const char* value(const ::aviot_srvs::ResetFenceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aviot_srvs::ResetFenceResponse> should match 
// service_traits::MD5Sum< ::aviot_srvs::ResetFence > 
template<>
struct MD5Sum< ::aviot_srvs::ResetFenceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aviot_srvs::ResetFence >::value();
  }
  static const char* value(const ::aviot_srvs::ResetFenceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aviot_srvs::ResetFenceResponse> should match 
// service_traits::DataType< ::aviot_srvs::ResetFence > 
template<>
struct DataType< ::aviot_srvs::ResetFenceResponse>
{
  static const char* value()
  {
    return DataType< ::aviot_srvs::ResetFence >::value();
  }
  static const char* value(const ::aviot_srvs::ResetFenceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AVIOT_SRVS_MESSAGE_RESETFENCE_H
