// Generated by gencpp from file aviot_srvs/SetFence.msg
// DO NOT EDIT!


#ifndef AVIOT_SRVS_MESSAGE_SETFENCE_H
#define AVIOT_SRVS_MESSAGE_SETFENCE_H

#include <ros/service_traits.h>


#include <aviot_srvs/SetFenceRequest.h>
#include <aviot_srvs/SetFenceResponse.h>


namespace aviot_srvs
{

struct SetFence
{

typedef SetFenceRequest Request;
typedef SetFenceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFence
} // namespace aviot_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aviot_srvs::SetFence > {
  static const char* value()
  {
    return "41ce895a5fb6ebba9f054f5ad0e7c544";
  }

  static const char* value(const ::aviot_srvs::SetFence&) { return value(); }
};

template<>
struct DataType< ::aviot_srvs::SetFence > {
  static const char* value()
  {
    return "aviot_srvs/SetFence";
  }

  static const char* value(const ::aviot_srvs::SetFence&) { return value(); }
};


// service_traits::MD5Sum< ::aviot_srvs::SetFenceRequest> should match 
// service_traits::MD5Sum< ::aviot_srvs::SetFence > 
template<>
struct MD5Sum< ::aviot_srvs::SetFenceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aviot_srvs::SetFence >::value();
  }
  static const char* value(const ::aviot_srvs::SetFenceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aviot_srvs::SetFenceRequest> should match 
// service_traits::DataType< ::aviot_srvs::SetFence > 
template<>
struct DataType< ::aviot_srvs::SetFenceRequest>
{
  static const char* value()
  {
    return DataType< ::aviot_srvs::SetFence >::value();
  }
  static const char* value(const ::aviot_srvs::SetFenceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aviot_srvs::SetFenceResponse> should match 
// service_traits::MD5Sum< ::aviot_srvs::SetFence > 
template<>
struct MD5Sum< ::aviot_srvs::SetFenceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aviot_srvs::SetFence >::value();
  }
  static const char* value(const ::aviot_srvs::SetFenceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aviot_srvs::SetFenceResponse> should match 
// service_traits::DataType< ::aviot_srvs::SetFence > 
template<>
struct DataType< ::aviot_srvs::SetFenceResponse>
{
  static const char* value()
  {
    return DataType< ::aviot_srvs::SetFence >::value();
  }
  static const char* value(const ::aviot_srvs::SetFenceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AVIOT_SRVS_MESSAGE_SETFENCE_H
