// Generated by gencpp from file aviot_srvs/DeleteFence.msg
// DO NOT EDIT!


#ifndef AVIOT_SRVS_MESSAGE_DELETEFENCE_H
#define AVIOT_SRVS_MESSAGE_DELETEFENCE_H

#include <ros/service_traits.h>


#include <aviot_srvs/DeleteFenceRequest.h>
#include <aviot_srvs/DeleteFenceResponse.h>


namespace aviot_srvs
{

struct DeleteFence
{

typedef DeleteFenceRequest Request;
typedef DeleteFenceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DeleteFence
} // namespace aviot_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aviot_srvs::DeleteFence > {
  static const char* value()
  {
    return "1b7306db77eae79388b7799e8c563252";
  }

  static const char* value(const ::aviot_srvs::DeleteFence&) { return value(); }
};

template<>
struct DataType< ::aviot_srvs::DeleteFence > {
  static const char* value()
  {
    return "aviot_srvs/DeleteFence";
  }

  static const char* value(const ::aviot_srvs::DeleteFence&) { return value(); }
};


// service_traits::MD5Sum< ::aviot_srvs::DeleteFenceRequest> should match 
// service_traits::MD5Sum< ::aviot_srvs::DeleteFence > 
template<>
struct MD5Sum< ::aviot_srvs::DeleteFenceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aviot_srvs::DeleteFence >::value();
  }
  static const char* value(const ::aviot_srvs::DeleteFenceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aviot_srvs::DeleteFenceRequest> should match 
// service_traits::DataType< ::aviot_srvs::DeleteFence > 
template<>
struct DataType< ::aviot_srvs::DeleteFenceRequest>
{
  static const char* value()
  {
    return DataType< ::aviot_srvs::DeleteFence >::value();
  }
  static const char* value(const ::aviot_srvs::DeleteFenceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aviot_srvs::DeleteFenceResponse> should match 
// service_traits::MD5Sum< ::aviot_srvs::DeleteFence > 
template<>
struct MD5Sum< ::aviot_srvs::DeleteFenceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aviot_srvs::DeleteFence >::value();
  }
  static const char* value(const ::aviot_srvs::DeleteFenceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aviot_srvs::DeleteFenceResponse> should match 
// service_traits::DataType< ::aviot_srvs::DeleteFence > 
template<>
struct DataType< ::aviot_srvs::DeleteFenceResponse>
{
  static const char* value()
  {
    return DataType< ::aviot_srvs::DeleteFence >::value();
  }
  static const char* value(const ::aviot_srvs::DeleteFenceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AVIOT_SRVS_MESSAGE_DELETEFENCE_H
