// Generated by gencpp from file aviot_srvs/GetFence.msg
// DO NOT EDIT!


#ifndef AVIOT_SRVS_MESSAGE_GETFENCE_H
#define AVIOT_SRVS_MESSAGE_GETFENCE_H

#include <ros/service_traits.h>


#include <aviot_srvs/GetFenceRequest.h>
#include <aviot_srvs/GetFenceResponse.h>


namespace aviot_srvs
{

struct GetFence
{

typedef GetFenceRequest Request;
typedef GetFenceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetFence
} // namespace aviot_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aviot_srvs::GetFence > {
  static const char* value()
  {
    return "466f87568982eee090da5c5e363b5143";
  }

  static const char* value(const ::aviot_srvs::GetFence&) { return value(); }
};

template<>
struct DataType< ::aviot_srvs::GetFence > {
  static const char* value()
  {
    return "aviot_srvs/GetFence";
  }

  static const char* value(const ::aviot_srvs::GetFence&) { return value(); }
};


// service_traits::MD5Sum< ::aviot_srvs::GetFenceRequest> should match 
// service_traits::MD5Sum< ::aviot_srvs::GetFence > 
template<>
struct MD5Sum< ::aviot_srvs::GetFenceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aviot_srvs::GetFence >::value();
  }
  static const char* value(const ::aviot_srvs::GetFenceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aviot_srvs::GetFenceRequest> should match 
// service_traits::DataType< ::aviot_srvs::GetFence > 
template<>
struct DataType< ::aviot_srvs::GetFenceRequest>
{
  static const char* value()
  {
    return DataType< ::aviot_srvs::GetFence >::value();
  }
  static const char* value(const ::aviot_srvs::GetFenceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aviot_srvs::GetFenceResponse> should match 
// service_traits::MD5Sum< ::aviot_srvs::GetFence > 
template<>
struct MD5Sum< ::aviot_srvs::GetFenceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aviot_srvs::GetFence >::value();
  }
  static const char* value(const ::aviot_srvs::GetFenceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aviot_srvs::GetFenceResponse> should match 
// service_traits::DataType< ::aviot_srvs::GetFence > 
template<>
struct DataType< ::aviot_srvs::GetFenceResponse>
{
  static const char* value()
  {
    return DataType< ::aviot_srvs::GetFence >::value();
  }
  static const char* value(const ::aviot_srvs::GetFenceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AVIOT_SRVS_MESSAGE_GETFENCE_H
