// Generated by gencpp from file aviot_srvs/GetFenceRequest.msg
// DO NOT EDIT!


#ifndef AVIOT_SRVS_MESSAGE_GETFENCEREQUEST_H
#define AVIOT_SRVS_MESSAGE_GETFENCEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aviot_srvs
{
template <class ContainerAllocator>
struct GetFenceRequest_
{
  typedef GetFenceRequest_<ContainerAllocator> Type;

  GetFenceRequest_()
    : frame(0)
    , polygon_id(0)  {
    }
  GetFenceRequest_(const ContainerAllocator& _alloc)
    : frame(0)
    , polygon_id(0)  {
  (void)_alloc;
    }



   typedef uint8_t _frame_type;
  _frame_type frame;

   typedef int32_t _polygon_id_type;
  _polygon_id_type polygon_id;



  enum {
    FRAME_GLOBAL = 0u,
    FRAME_LOCAL_NED = 1u,
    FRAME_LOCAL_ENU = 4u,
    FRAME_GLOBAL_INT = 5u,
    FRAME_LOCAL_OFFSET_NED = 7u,
  };


  typedef boost::shared_ptr< ::aviot_srvs::GetFenceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aviot_srvs::GetFenceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetFenceRequest_

typedef ::aviot_srvs::GetFenceRequest_<std::allocator<void> > GetFenceRequest;

typedef boost::shared_ptr< ::aviot_srvs::GetFenceRequest > GetFenceRequestPtr;
typedef boost::shared_ptr< ::aviot_srvs::GetFenceRequest const> GetFenceRequestConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aviot_srvs::GetFenceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aviot_srvs::GetFenceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aviot_srvs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aviot_srvs::GetFenceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aviot_srvs::GetFenceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aviot_srvs::GetFenceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aviot_srvs::GetFenceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aviot_srvs::GetFenceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aviot_srvs::GetFenceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aviot_srvs::GetFenceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "47655ecd027caeafcc9cd21438352a34";
  }

  static const char* value(const ::aviot_srvs::GetFenceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x47655ecd027caeafULL;
  static const uint64_t static_value2 = 0xcc9cd21438352a34ULL;
};

template<class ContainerAllocator>
struct DataType< ::aviot_srvs::GetFenceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aviot_srvs/GetFenceRequest";
  }

  static const char* value(const ::aviot_srvs::GetFenceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aviot_srvs::GetFenceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 frame\n\
uint8 FRAME_GLOBAL = 0\n\
uint8 FRAME_LOCAL_NED = 1\n\
uint8 FRAME_LOCAL_ENU = 4\n\
uint8 FRAME_GLOBAL_INT = 5\n\
uint8 FRAME_LOCAL_OFFSET_NED = 7\n\
int32 polygon_id\n\
";
  }

  static const char* value(const ::aviot_srvs::GetFenceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aviot_srvs::GetFenceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frame);
      stream.next(m.polygon_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetFenceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aviot_srvs::GetFenceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aviot_srvs::GetFenceRequest_<ContainerAllocator>& v)
  {
    s << indent << "frame: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.frame);
    s << indent << "polygon_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.polygon_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AVIOT_SRVS_MESSAGE_GETFENCEREQUEST_H
