// Generated by gencpp from file aviot_srvs/GetFenceResponse.msg
// DO NOT EDIT!


#ifndef AVIOT_SRVS_MESSAGE_GETFENCERESPONSE_H
#define AVIOT_SRVS_MESSAGE_GETFENCERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace aviot_srvs
{
template <class ContainerAllocator>
struct GetFenceResponse_
{
  typedef GetFenceResponse_<ContainerAllocator> Type;

  GetFenceResponse_()
    : frame(0)
    , mode(0)
    , points()  {
    }
  GetFenceResponse_(const ContainerAllocator& _alloc)
    : frame(0)
    , mode(0)
    , points(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _frame_type;
  _frame_type frame;

   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _points_type;
  _points_type points;



  enum {
    FRAME_GLOBAL = 0u,
    FRAME_LOCAL_NED = 1u,
    FRAME_LOCAL_ENU = 4u,
    FRAME_GLOBAL_INT = 5u,
    FRAME_LOCAL_OFFSET_NED = 7u,
    MODE_DENY = 0u,
    MODE_ALLOW = 1u,
  };


  typedef boost::shared_ptr< ::aviot_srvs::GetFenceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aviot_srvs::GetFenceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetFenceResponse_

typedef ::aviot_srvs::GetFenceResponse_<std::allocator<void> > GetFenceResponse;

typedef boost::shared_ptr< ::aviot_srvs::GetFenceResponse > GetFenceResponsePtr;
typedef boost::shared_ptr< ::aviot_srvs::GetFenceResponse const> GetFenceResponseConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aviot_srvs::GetFenceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aviot_srvs::GetFenceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aviot_srvs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aviot_srvs::GetFenceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aviot_srvs::GetFenceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aviot_srvs::GetFenceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aviot_srvs::GetFenceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aviot_srvs::GetFenceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aviot_srvs::GetFenceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aviot_srvs::GetFenceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a6b013422cbf99acfc1ef2f7fe5aa28c";
  }

  static const char* value(const ::aviot_srvs::GetFenceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa6b013422cbf99acULL;
  static const uint64_t static_value2 = 0xfc1ef2f7fe5aa28cULL;
};

template<class ContainerAllocator>
struct DataType< ::aviot_srvs::GetFenceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aviot_srvs/GetFenceResponse";
  }

  static const char* value(const ::aviot_srvs::GetFenceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aviot_srvs::GetFenceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 frame\n\
uint8 FRAME_GLOBAL = 0\n\
uint8 FRAME_LOCAL_NED = 1\n\
uint8 FRAME_LOCAL_ENU = 4\n\
uint8 FRAME_GLOBAL_INT = 5\n\
uint8 FRAME_LOCAL_OFFSET_NED = 7\n\
\n\
uint8 mode\n\
uint8 MODE_DENY = 0\n\
uint8 MODE_ALLOW = 1\n\
geometry_msgs/Point[] points\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::aviot_srvs::GetFenceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aviot_srvs::GetFenceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frame);
      stream.next(m.mode);
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetFenceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aviot_srvs::GetFenceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aviot_srvs::GetFenceResponse_<ContainerAllocator>& v)
  {
    s << indent << "frame: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.frame);
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AVIOT_SRVS_MESSAGE_GETFENCERESPONSE_H
