// Generated by gencpp from file aviot_srvs/ListFence.msg
// DO NOT EDIT!


#ifndef AVIOT_SRVS_MESSAGE_LISTFENCE_H
#define AVIOT_SRVS_MESSAGE_LISTFENCE_H

#include <ros/service_traits.h>


#include <aviot_srvs/ListFenceRequest.h>
#include <aviot_srvs/ListFenceResponse.h>


namespace aviot_srvs
{

struct ListFence
{

typedef ListFenceRequest Request;
typedef ListFenceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ListFence
} // namespace aviot_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aviot_srvs::ListFence > {
  static const char* value()
  {
    return "f34d918e24ff52b99229c78d4dfce377";
  }

  static const char* value(const ::aviot_srvs::ListFence&) { return value(); }
};

template<>
struct DataType< ::aviot_srvs::ListFence > {
  static const char* value()
  {
    return "aviot_srvs/ListFence";
  }

  static const char* value(const ::aviot_srvs::ListFence&) { return value(); }
};


// service_traits::MD5Sum< ::aviot_srvs::ListFenceRequest> should match 
// service_traits::MD5Sum< ::aviot_srvs::ListFence > 
template<>
struct MD5Sum< ::aviot_srvs::ListFenceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aviot_srvs::ListFence >::value();
  }
  static const char* value(const ::aviot_srvs::ListFenceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aviot_srvs::ListFenceRequest> should match 
// service_traits::DataType< ::aviot_srvs::ListFence > 
template<>
struct DataType< ::aviot_srvs::ListFenceRequest>
{
  static const char* value()
  {
    return DataType< ::aviot_srvs::ListFence >::value();
  }
  static const char* value(const ::aviot_srvs::ListFenceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aviot_srvs::ListFenceResponse> should match 
// service_traits::MD5Sum< ::aviot_srvs::ListFence > 
template<>
struct MD5Sum< ::aviot_srvs::ListFenceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aviot_srvs::ListFence >::value();
  }
  static const char* value(const ::aviot_srvs::ListFenceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aviot_srvs::ListFenceResponse> should match 
// service_traits::DataType< ::aviot_srvs::ListFence > 
template<>
struct DataType< ::aviot_srvs::ListFenceResponse>
{
  static const char* value()
  {
    return DataType< ::aviot_srvs::ListFence >::value();
  }
  static const char* value(const ::aviot_srvs::ListFenceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AVIOT_SRVS_MESSAGE_LISTFENCE_H
