// Generated by gencpp from file aviot_srvs/ResetFenceRequest.msg
// DO NOT EDIT!


#ifndef AVIOT_SRVS_MESSAGE_RESETFENCEREQUEST_H
#define AVIOT_SRVS_MESSAGE_RESETFENCEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aviot_srvs
{
template <class ContainerAllocator>
struct ResetFenceRequest_
{
  typedef ResetFenceRequest_<ContainerAllocator> Type;

  ResetFenceRequest_()
    {
    }
  ResetFenceRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::aviot_srvs::ResetFenceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aviot_srvs::ResetFenceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ResetFenceRequest_

typedef ::aviot_srvs::ResetFenceRequest_<std::allocator<void> > ResetFenceRequest;

typedef boost::shared_ptr< ::aviot_srvs::ResetFenceRequest > ResetFenceRequestPtr;
typedef boost::shared_ptr< ::aviot_srvs::ResetFenceRequest const> ResetFenceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aviot_srvs::ResetFenceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aviot_srvs::ResetFenceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aviot_srvs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'HasHeader': False, 'IsMessage': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aviot_srvs::ResetFenceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aviot_srvs::ResetFenceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aviot_srvs::ResetFenceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aviot_srvs::ResetFenceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aviot_srvs::ResetFenceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aviot_srvs::ResetFenceRequest_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aviot_srvs::ResetFenceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::aviot_srvs::ResetFenceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::aviot_srvs::ResetFenceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aviot_srvs/ResetFenceRequest";
  }

  static const char* value(const ::aviot_srvs::ResetFenceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aviot_srvs::ResetFenceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::aviot_srvs::ResetFenceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aviot_srvs::ResetFenceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResetFenceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aviot_srvs::ResetFenceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::aviot_srvs::ResetFenceRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // AVIOT_SRVS_MESSAGE_RESETFENCEREQUEST_H
