// Generated by gencpp from file aviot_srvs/SetFenceResponse.msg
// DO NOT EDIT!


#ifndef AVIOT_SRVS_MESSAGE_SETFENCERESPONSE_H
#define AVIOT_SRVS_MESSAGE_SETFENCERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aviot_srvs
{
template <class ContainerAllocator>
struct SetFenceResponse_
{
  typedef SetFenceResponse_<ContainerAllocator> Type;

  SetFenceResponse_()
    : polygon_id(0)  {
    }
  SetFenceResponse_(const ContainerAllocator& _alloc)
    : polygon_id(0)  {
  (void)_alloc;
    }



   typedef int32_t _polygon_id_type;
  _polygon_id_type polygon_id;



  enum {
    E_INVALID_POLYGON = -1,
    E_INVALID_MODE = -2,
    E_INVALID_FRAME = -3,
  };


  typedef boost::shared_ptr< ::aviot_srvs::SetFenceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aviot_srvs::SetFenceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetFenceResponse_

typedef ::aviot_srvs::SetFenceResponse_<std::allocator<void> > SetFenceResponse;

typedef boost::shared_ptr< ::aviot_srvs::SetFenceResponse > SetFenceResponsePtr;
typedef boost::shared_ptr< ::aviot_srvs::SetFenceResponse const> SetFenceResponseConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aviot_srvs::SetFenceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aviot_srvs::SetFenceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aviot_srvs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::aviot_srvs::SetFenceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aviot_srvs::SetFenceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aviot_srvs::SetFenceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aviot_srvs::SetFenceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aviot_srvs::SetFenceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aviot_srvs::SetFenceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aviot_srvs::SetFenceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b8cdd29592fb1598878c7cb60a49e26";
  }

  static const char* value(const ::aviot_srvs::SetFenceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b8cdd29592fb159ULL;
  static const uint64_t static_value2 = 0x8878c7cb60a49e26ULL;
};

template<class ContainerAllocator>
struct DataType< ::aviot_srvs::SetFenceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aviot_srvs/SetFenceResponse";
  }

  static const char* value(const ::aviot_srvs::SetFenceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aviot_srvs::SetFenceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 polygon_id\n\
int32 E_INVALID_POLYGON = -1\n\
int32 E_INVALID_MODE = -2\n\
int32 E_INVALID_FRAME = -3\n\
\n\
";
  }

  static const char* value(const ::aviot_srvs::SetFenceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aviot_srvs::SetFenceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.polygon_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetFenceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aviot_srvs::SetFenceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aviot_srvs::SetFenceResponse_<ContainerAllocator>& v)
  {
    s << indent << "polygon_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.polygon_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AVIOT_SRVS_MESSAGE_SETFENCERESPONSE_H
